Substitute the exact formulas for the meridional and normal curvatures.
mapbox/cheap-ruler-cpp pull request #13
Opened 2018-04-25 18:59 UTC by cffk

The FCC formulas have a few drawbacks:

* They involve "magic constants" (given with a limited number of significant digits) with no indication of where they come from.
* They are based on the Clarke ellipsoid dating back to 1866 so are inconsistent with most modern GIS systems which use the WGS84 ellipsoid.
* They are written as truncated trigonometric series.  There's absolutely no reason not to use the exact expressions (which are simpler!).  (Expanding the exact expressions was traditionally done in order to perform integration leading to a series approximation of the elliptic integral.  But that's not an issues here.

Because these latitude and longitude coefficients are now exact, several tests (based on the series approximation) now fail.  I've left in place the Clarke 1866 parameters.  I recommend that the WGS84 parameters be substituted in the process of updating the tests.

I realize that cheap-ruler is already approximate, so why quibble about the coefficients?  Two reasons:

* The new formulas are accurate in limit of small distance.
* 50 years from now, no-one will be able to figure out what the old formulas mean.

2018-04-25 22:30 UTC, cffk commented
The coefficients in the FCC formulas are only quoted to the nearest centimeter.  The tests should therefore allow an error of at least this amount (5 cm might be reasonable).  Once the tests are updated for the new formulas, the error tolerance in the tests could be tightened, e.g., to 0.1 mm.

2018-04-26 06:01 UTC, mourner requested changes
This is great! Let's update the ellipsoid and the tests.

2018-04-26 15:41 UTC, cffk commented
I'll update the tests...  I notice that `assertErr` implements a *relative* error check; but almost always in GIS applications an *absolute* error check make more sense.  For example, it's silly that the tests for the bearing are more rigorous near due north rather than due south.  So I propose to switch `assertErr` to doing an absolute error check.  Where a relative check really is needed, this can be accomplished in how `assertErr` is called.

2018-04-26 15:52 UTC, mourner commented
Yeah, agreed about the error checking.

2018-05-12 20:11 UTC, cffk commented
I recommend deferring the update to the ellipsoid and the redoing of the tests to a separate pull request.  As it stands, the formulas are in a saner form and the existing tests are all working.  It would be good to know how the existing "good" results for tests were created so that I know how to update them for WGS84.

2020-04-17 11:19 UTC, vng commented
Here is the updated version: https://github.com/mapbox/cheap-ruler-cpp/pull/17

2020-04-17 11:19 UTC, closed without merging